// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `LIGHTCLIENT`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `initialize`

/// Check if a wallet exists
Future<bool> walletExists({required String chainName}) =>
    RustLib.instance.api.crateApiWalletExists(chainName: chainName);

/// Initialize a new wallet and return the seed phrase
Future<String> initializeNew({required String serverUri}) =>
    RustLib.instance.api.crateApiInitializeNew(serverUri: serverUri);

/// Initialize from an existing wallet
Future<String> initializeExisting({required String serverUri}) =>
    RustLib.instance.api.crateApiInitializeExisting(serverUri: serverUri);

/// Initialize from seed phrase
Future<String> initializeFromPhrase(
        {required String serverUri,
        required String seedPhrase,
        required BigInt birthday,
        required bool overwrite}) =>
    RustLib.instance.api.crateApiInitializeFromPhrase(
        serverUri: serverUri,
        seedPhrase: seedPhrase,
        birthday: birthday,
        overwrite: overwrite);

/// Execute a command (main wallet interface)
Future<String> execute({required String command, required String args}) =>
    RustLib.instance.api.crateApiExecute(command: command, args: args);

/// Deinitialize the wallet
Future<String> deinitialize() => RustLib.instance.api.crateApiDeinitialize();

/// Get sync status
String getSyncStatus() => RustLib.instance.api.crateApiGetSyncStatus();

/// Sync the wallet
Future<String> sync_() => RustLib.instance.api.crateApiSync();

/// Get balance
String getBalance() => RustLib.instance.api.crateApiGetBalance();

/// Get transaction list
String getTransactions() => RustLib.instance.api.crateApiGetTransactions();

/// Send transaction
Future<String> sendTransaction(
        {required String address, required BigInt amount, String? memo}) =>
    RustLib.instance.api
        .crateApiSendTransaction(address: address, amount: amount, memo: memo);

/// Get addresses
String getAddresses() => RustLib.instance.api.crateApiGetAddresses();

/// Generate new address
String newAddress({required String addressType}) =>
    RustLib.instance.api.crateApiNewAddress(addressType: addressType);

/// Get wallet height
int getHeight() => RustLib.instance.api.crateApiGetHeight();

/// Get info
String getInfo() => RustLib.instance.api.crateApiGetInfo();
