// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'message_label.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

MessageLabel _$MessageLabelFromJson(Map<String, dynamic> json) => MessageLabel(
      id: (json['id'] as num?)?.toInt(),
      txid: json['txid'] as String,
      labelName: json['labelName'] as String,
      labelColor: json['labelColor'] as String? ?? '#2196F3',
      isAutoGenerated: json['isAutoGenerated'] as bool? ?? false,
      createdAt: DateTime.parse(json['createdAt'] as String),
      updatedAt: DateTime.parse(json['updatedAt'] as String),
    );

Map<String, dynamic> _$MessageLabelToJson(MessageLabel instance) =>
    <String, dynamic>{
      'id': instance.id,
      'txid': instance.txid,
      'labelName': instance.labelName,
      'labelColor': instance.labelColor,
      'isAutoGenerated': instance.isAutoGenerated,
      'createdAt': instance.createdAt.toIso8601String(),
      'updatedAt': instance.updatedAt.toIso8601String(),
    };
